---

- name: install nginx
  become: yes
  package:
    name: nginx
    state: latest

- name: ensure nginx service is enabled
  become: yes
  service:
    name: nginx
    enabled: yes

- name: remove default nginx site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: add rate limiting
  become: yes
  copy:
    dest: /etc/nginx/conf.d/metabase-rate-limit.conf
    content: |
      limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;
  notify: restart nginx

- name: create nginx kuma.conf
  become: yes
  template:
    src: kuma.conf.j2
    dest: "/etc/nginx/conf.d/kuma.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: fix SEL permissions
  become: yes
  shell: setsebool httpd_can_network_connect on -P
