---
# playbook file to set up the machine and install Decidim

- hosts: all
  gather_facts: yes
  roles:
    - role: init_container
    - role: podman
    - role: kuma
    - role: nginx
    - role: letsencrypt
