---
# tasks file for init_container

- name: upgrade all packages
  become: yes
  dnf:
    name: '*'
    state: 'latest'
  when: ansible_facts['os_family'] == "RedHat"

- name: set machine timezone to "{{ timezone }}"
  become: yes
  timezone:
    name: "{{ timezone }}"