---
# tasks file for metabase

- name: Create the kuma container
  containers.podman.podman_container:
    name: kuma
    image: docker.io/louislam/uptime-kuma
    recreate: yes
    ports:
      - "3001:3001"
    restart_policy: always
    volumes:
      - uptime-kuma:/app/data