---

- name: install certbot package - install epel
  become: yes
  dnf:
    name: epel-release
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: install certbot package - install certbot
  become: yes
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - certbot
    - python3-certbot-nginx
  when: ansible_facts['os_family'] == "RedHat"

- name: Check if certificate already exists.
  become: yes
  stat:
    path: /etc/letsencrypt/live/{{ domain }}/cert.pem
  register: letsencrypt_cert

# TODO http2 is not yet suppported by certbot (fix here and in template)
- name: configure certbot (please check results at https://www.ssllabs.com/ssltest/analyze.html?d={{ domain }} )
  become: yes
  # use -v to debug
  shell: "certbot --non-interactive --preferred-challenges http --agree-tos --email {{ letsencrypt_admin_email }} --nginx -d {{ domain }}"

- name: set certificate permissions
  become: yes
  file:
    path: /etc/letsencrypt/live
    recurse: yes
    owner: root
    group: nginx
    mode: 0755
  notify: restart nginx

- name: Enable certbot-renew timer
  become: yes
  systemd:
    name: certbot-renew
    state: started
